### ISSUE TITLE
NVDA Вылетает на неизвестных символах

### ISSUE THREAD

**Issue by alekssamos** [Olga-Yakovleva/RHVoice#235]
Если встретится какой-нибудь символ наподобие '\ud83e'
то произойдёт ошибка.
Если в Firefox листать стрелкой вниз или вверх, продолжение невозможно, виртуальный буфер вылетит и пролистать не получится.
Скорее всего, поможет аргумент errors='ignore' у функции decode? Или Try Except на крайний случай ?
```
IO - inputCore.InputManager.executeGesture (05:32:40.789) - winInputHook (6884):
Input: kb(laptop):NVDA+c
IO - speech.speak (05:32:40.805) - MainThread (6248):
Speaking ['<span class="peer_initials nocopy im_message_from_photo user_bgcolor_1" data-content="a\ud83e"></span>']
ERROR - scriptHandler.executeScript (05:32:40.805) - MainThread (6248):
error executing script: <bound method GlobalCommands.script_reportClipboardText of <globalCommands.GlobalCommands object at 0x03646CD0>> with gesture 'NVDA+c'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "globalCommands.pyc", line 2165, in script_reportClipboardText
  File "ui.pyc", line 77, in message
  File "speech\__init__.pyc", line 183, in speakMessage
  File "speech\__init__.pyc", line 786, in speak
  File "speech\manager.pyc", line 276, in speak
  File "speech\manager.pyc", line 424, in _pushNextSpeech
  File "C:\Users\Alexey\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 822, in speak
    task=speak_text(self.__lib,self.__tts_engine,text,self.__cancel_flag,self.__player)
  File "C:\Users\Alexey\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 397, in __init__
    self.__text=text.encode("utf-8")
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83e' in position 197: surrogates not allowed
```

**Comment by alekssamos** [comment]
Я исправил эту ошибку.
Теперь всё хорошо и можно листать дальше.

**Comment by alex19EP** [comment]
let's it be opened until pr is merged.
